---
title: "Contenido en el repositorio de GitHub"
subtitle: "Códigos para diferentes trabajos en R y algunos análisis estadísticos de interés"
author: "Andres M. Palacio"
output: pdf_document
fig_caption: yes
latex_engine: xelatex
number_sections: yes
toc: yes
date: '\today'
linkcolor: blue
urlcolor: blue
---

\pagebreak     


# Bases de datos para el desarrollo de ejercicios

- DANE
- Ministerio de Salud y Protección Social
- Banco de la República
- OCDE
- Banco Mundial


\pagebreak


# Competencias en Kaggle

## Titanic

- [Datos para la Competencia](https://www.kaggle.com/competitions/titanic)
- [Fuente de ayuda](https://pyoflife.com/exploring-the-titanic-dataset-with-r-a-beginners-guide-to-eda-pdf/)
- [Código y análisis] ()

\pagebreak

## Medicina Personalizada - EDA con tidy R

- [Datos para la Competencia](https://www.google.com/search?q=traductor&rlz=1C1CHZN_esCO1010CO1010&oq=tradu&aqs=chrome.1.69i57j69i59j0i67i650j0i67i131i433i650j0i67i650j0i512j0i131i433i512l4.1712j0j7&sourceid=chrome&ie=UTF-8)
- [Código y análisis] ()

\pagebreak

# GitHub

## Archivo Readme

- [Fuente]()

\pagebreak

## Un blog en GitHub y Jekyll

- [Fuente](https://www.blogpocket.com/2018/09/02/tener-un-blog-con-github-y-jekyll/)

\pagebreak

# Aspectos básicos en R

## Tablas de frecuencias

 - [Código](https://github.com/AndresMPL/Descriptive_Statistics/blob/main/frequency_tables.R)

\pagebreak


## Sum Across Columns in R -- dplyr & base

- [Fuente]()

\pagebreak

## Loops en R

- [Fuente](https://statisticsglobe.com/loops-in-r/)

\pagebreak

## Creación de Funciones

- [Fuente](https://www.rforecology.com/post/how-to-create-your-own-function-in-r/)

\pagebreak

## Obtener, limpiar y manipular datos

-  [Fuente](https://www.bigbookofr.com/getting-cleaning-and-wrangling-data.html)

\pagebreak

## Índices y función lapply

- [Fuente](https://finnstats.com/index.php/2022/01/11/index-names-and-lapply-function-in-r/)

\pagebreak

## Merge

- [Fuente](https://pyoflife.com/introduction-to-geospatial-visualization-with-the-tmap-package/)

\pagebreak

## Generación de secuencias de números en R con: seq() y rep()

- [Fuente](https://www.marsja.se/how-to-generate-a-sequence-of-numbers-in-r-with-seq-and-rep/)

\pagebreak

# Visualización de datos

- [Fuente](https://socviz.co/)

\pagebreak

## Visualización Geoespacial

- [Fuente 1](https://www.bigbookofr.com/geospatial.html)
- [Fuente 2 - tmap](https://pyoflife.com/introduction-to-geospatial-visualization-with-the-tmap-package/)

\pagebreak

## Gráficos ggplot2

-   [Fuente](https://github.com/erikgahner/awesome-ggplot2#readme)

\pagebreak

# Procesamiento de texto 

- [Fuente](https://programminghistorian.org/es/lecciones/procesamiento-basico-de-textos-en-r> - <https://www.bigbookofr.com/text-analysis.html)

\pagebreak

# Análisis estadístico

## Análisis de series de tiempo y pronósticos

- [Fuente](https://www.bigbookofr.com/time-series-analysis-and-forecasting.html)

\pagebreak

## Teorema del límite central

- [Fuente](https://pyoflife.com/learn-the-central-limit-theorem-in-r/)

\pagebreak

## Valores atípicos

- [Fuente](https://towardsdatascience.com/outlier-detection-using-distribution-fitting-in-univariate-data-sets-ac8b7a14d40e)

\pagebreak

## Comparación de Varianzas

- [Fuente](https://datasciencetut.com/how-to-compare-variances-in-r/)

\pagebreak

# Análisis Econométrico

- [Fuente](https://www.bigbookofr.com/finance.html#using-r-for-introductory-econometrics)

\pagebreak

# Reportes

- [Fuente](https://www.bigbookofr.com/reports.html)


\pagebreak


# HTML en R

## webR Code Extension for Quarto HTML Documents

-   [Fuente](https://github.com/coatless/quarto-webr#install-on-an-as-needed-basis)

\pagebreak

# Ejercicios

## Libro *"Introducción a la microeconometría básica con aplicaciones en R"*
**Revilla, 2020. Universidad de la Salle.**


\pagebreak


## Libro *"Métodos matemáticos y computacionales en Macroeconometría"*
**Villegas, 2009. Universidad de los Andes.**


\pagebreak


## Libro *"Modelos de crecimiento económico en R"*
**Fentanes, Quintana, Garza, 2022. Alpha Editorial.**


\pagebreak


# Lecturas generales

## Libro de códigos

- [Fuente](https://rpubs.com/medusa/91225)

\pagebreak

## Los básicos de R

- [Fuente](https://coaching.rforecology.com/)

\pagebreak

## Tutoriales introductorios

- [Fuente](https://www.r-bloggers.com/2015/12/how-to-learn-r-2/)

\pagebreak

## Funciones esenciales de R

- [Fuente](https://www.rforecology.com/post/the-essential-functions-of-r-cheatsheet/)

\pagebreak

## Programación en R

- [Fuente](https://www.bigbookofr.com/r-programming.html>)

\pagebreak


# Artículos de interés

- [R, herramienta de científicos de datos](https://www.enae.es/blog/lenguaje-r-la-herramienta-de-los-cientificos-de-datos?_adin=0745282514#gref)
- [Matemáticas en ciencia de datos](https://pub.towardsai.net/how-much-math-do-i-need-in-data-science-d05d83f8cb19)
- [Competencias en ciencias de datos](https://www.kdnuggets.com/2023/04/top-19-skills-need-know-2023-data-scientist.html)

\pagebreak

# Libros relacionados

-   [Introduction to Probability for Data Science](https://probability4datascience.com/)
-   [Libros gratis PDF para aprender R en Español](https://aprendiendoinformatica.com/2020/06/libros-pdf-gratis-para-aprender-r-en-espanol/)
-   [Statistics](https://www.bigbookofr.com/statistics.html)
-   [Understanding Deep Learning](https://udlbook.github.io/udlbook/)

\pagebreak



